const data = {
  courses: [
    {
      id: "3",
      course: "CFM APD (LOE)",
      idFamily: "2",
      vliteral: "AtenciÃ³ a persones en situaciÃ³ de dependÃ¨ncia",
      cliteral: "AtenciÃ³n a personas en situaciÃ³n de dependencia",
    },
    {
      id: "4",
      course: "CFM FARMACIA (LOE)",
      idFamily: "6",
      vliteral: "FarmÃ cia i parafarmÃ cia",
      cliteral: "Farmacia y parafarmacia",
    },
    {
      id: "8",
      course: "CFM CAE (LOGSE)",
      idFamily: "6",
      vliteral: "Cures auxiliares d'infermeria",
      cliteral: "Cuidados auxiliares de enfermerÃ­a",
    },
    {
      id: "12",
      course: "CFM CUINA (LOE)",
      idFamily: "10",
      vliteral: "Cuina i gastronomia",
      cliteral: "Cocina y gastronomÃ­a",
    },
    {
      id: "16",
      course: "CFM ESTÃˆTICA I BELL. (LOE)",
      idFamily: "3",
      vliteral: "EstÃ¨tica i bellesa",
      cliteral: "EstÃ©tica y belleza",
    },
    {
      id: "18",
      course: "CFM GESTIÃ“ ADMVA. (LOE)",
      idFamily: "5",
      vliteral: "GestiÃ³ administrativa",
      cliteral: "GestiÃ³n administrativa",
    },
    {
      id: "20",
      course: "CFM PERRUQUERIA (LOE)",
      idFamily: "3",
      vliteral: "Perruqueria i cosmÃ¨tica capilar",
      cliteral: "PeluquerÃ­a y cosmÃ©tica capilar",
    },
    {
      id: "22",
      course: "CFM SERV. RESTAURACIÃ“ (LOE)",
      idFamily: "10",
      vliteral: "Servicis en restauraciÃ³",
      cliteral: "Servicios en restauraciÃ³n",
    },
    {
      id: "24",
      course: "CFM SMX  (LOE)",
      idFamily: "24",
      vliteral: "Sistemes microinformÃ tics i xarxes",
      cliteral: "Sistemas microinformÃ¡ticos y redes",
    },
    {
      id: "28",
      course: "CFS ADM. I FINANC. (LOE)",
      idFamily: "5",
      vliteral: "AdministraciÃ³ i finances",
      cliteral: "AdministraciÃ³n y finanzas",
    },
    {
      id: "29",
      course: "CFS ASSISTENCIA A LA DIRECCIÃ“ (LOE)",
      idFamily: "5",
      vliteral: "AssitÃ¨ncia a la direcciÃ³",
      cliteral: "Asistencia a la direcciÃ³n",
    },
    {
      id: "30",
      course: "CFS ASIX (LOE)",
      idFamily: "24",
      vliteral: "AdministraciÃ³ de sistemes informÃ tics en xarxa",
      cliteral: "AdministraciÃ³n de sistemas informÃ¡ticos en red",
    },
    {
      id: "32",
      course: "CFS DAM (LOE)",
      idFamily: "24",
      vliteral: "Desenrotllament d'aplicacions multiplataforma",
      cliteral: "Desarrollo de aplicaciones multiplataforma",
    },
    {
      id: "35",
      course: "CFS DAW (LOE)",
      idFamily: "24",
      vliteral: "Desenrotllament d'aplicacions web",
      cliteral: "Desarrollo de aplicaciones  web",
    },
    {
      id: "36",
      course: "CFS DIREC. CUINA (LOE)",
      idFamily: "10",
      vliteral: "DirecciÃ³ de cuina",
      cliteral: "DirecciÃ³n de cocina",
    },
    {
      id: "38",
      course: "CFS DIREC.RESTAURACIÃ“ (LOE)",
      idFamily: "10",
      vliteral: "DirecciÃ³ en servicis de restauraciÃ³",
      cliteral: "DirecciÃ³n en servicios de restauraciÃ³n",
    },
    {
      id: "39",
      course: "CFS EDUC.INFANTIL (LOE)",
      idFamily: "2",
      vliteral: "EducaciÃ³ infantil",
      cliteral: "EducaciÃ³n infantil",
    },
    {
      id: "42",
      course: "CFS ESTET.INTEG. (LOE)",
      idFamily: "3",
      vliteral: "EstÃ¨tica integral i benestar",
      cliteral: "EstÃ©tica integral y bienestar",
    },
    {
      id: "44",
      course: "CFS INTEGR.SOCIAL (LOE)",
      idFamily: "2",
      vliteral: "IntegraciÃ³ Social",
      cliteral: "IntegraciÃ³n Social",
    },
    {
      id: "45",
      course: "CFS LABORATORI (LOE)",
      idFamily: "6",
      vliteral: "Laboratori clÃ­nic i biomÃ¨dic",
      cliteral: "Laboratorio clinico y biomÃ©dico",
    },
    {
      id: "51",
      course: "CFS RXMN (LOE)",
      idFamily: "6",
      vliteral: "Imatge per al diagnÃ²tic i medicina nuclear",
      cliteral: "Imagen para el diagnÃ³stico y medicina nuclear",
    },
    {
      id: "54",
      course: "CFS SALUT AMBIENTAL (LOGSE)",
      idFamily: "6",
      vliteral: "Salut ambiental",
      cliteral: "Salud ambiental",
    },
    {
      id: "56",
      course: "CFS TASOCIT (LOE)",
      idFamily: "2",
      vliteral: "AnimaciÃ³ Sociocultural i turÃ­stica",
      cliteral: "AnimaciÃ³n Sociocultural y turÃ­stica",
    },
    {
      id: "57",
      course: "TPB Perruqueria i EstÃ©tica",
      idFamily: "3",
      vliteral: "FP BÃ sica Perruqueria i EstÃ¨tica",
      cliteral: "FP BÃ¡sica Peluqueria i EstÃ©tica",
    },
    {
      id: "58",
      course: "CFS QUIMICA I SALUT AMBIENTAL",
      idFamily: "25",
      vliteral: "QuÃ­mica i Salut Ambiental",
      cliteral: "QuÃ­mica i Salut Ambiental",
    },
    {
      id: "59",
      course: "MASTER CIBERSEGURETAT",
      idFamily: "24",
      vliteral:
        "Curs d'EspecialiTzaciÃ³ en Ciberseguretat en Entorns de les Tecnologies de la InformaciÃ³n",
      cliteral:
        "Curso de EspecializaciÃ³n en Ciberseguridad en Entornos de las TecnologÃ­as de la InformaciÃ³n",
    },
  ],
  families: [
    {
      id: "1",
      cliteral: "INGLES",
      vliteral: "ANGLES",
    },
    {
      id: "2",
      cliteral: "SERVICIOS A LA COMUNIDAD",
      vliteral: "SEVEIS A LA COMUNITAT",
    },
    {
      id: "3",
      cliteral: "IMAGEN PERSONAL",
      vliteral: "IMATGE PERSONAL",
    },
    {
      id: "5",
      cliteral: "DEPARTAMENTO ADMINISTRATIVO",
      vliteral: "DEPARTAMENT ADMINISTRACIÃ“",
    },
    {
      id: "6",
      cliteral: "DEPARTAMENTO SANITARIO",
      vliteral: "DEPARTAMENT SANITARI",
    },
    {
      id: "9",
      cliteral: "EXTENSION CULTURAL",
      vliteral: "EXTENSIO CULTURAL",
    },
    {
      id: "10",
      cliteral: "HOSTELERIA Y TURISMO",
      vliteral: "HOSTELERIA I TURISME",
    },
    {
      id: "12",
      cliteral: "FORMACION Y ORIENTACION LABORA",
      vliteral: "FORMACIO I ORIENTACIO LABORAL",
    },
    {
      id: "18",
      cliteral: "ORIENTACION",
      vliteral: "ORIENTACIO",
    },
    {
      id: "24",
      cliteral: "DEPARTAMENTO INFORMATICA",
      vliteral: "DEPARTAMENT INFORMÃ€TICA",
    },
    {
      id: "25",
      cliteral: "Seguridad y Medio Ambiente",
      vliteral: "Seguretat i Medi Ambient",
    },
  ],
  modules: [
    {
      code: "0011",
      cliteral: "DidÃ¡ctica de la educaciÃ³n infantil",
      vliteral: "DidÃ ctica de l'educaciÃ³n infantil",
      idCourse: "39",
    },
    {
      code: "0012",
      cliteral: "AutonomÃ­a personal y salud infantil",
      vliteral: "Autonomia personal i salut infantil",
      idCourse: "39",
    },
    {
      code: "0013",
      cliteral: "El juego infantil y su metodologÃ­a",
      vliteral: "El joc infantil i la seua metodolog",
      idCourse: "39",
    },
    {
      code: "0014",
      cliteral: "ExpresiÃ³n y comunicaciÃ³n",
      vliteral: "ExpressiÃ³ i comunicaciÃ³",
      idCourse: "39",
    },
    {
      code: "0015",
      cliteral: "Desarrollo cognitivo y motor",
      vliteral: "Desenrotllament cognitiu i motor",
      idCourse: "39",
    },
    {
      code: "0016",
      cliteral: "Desarrollo socioafectivo",
      vliteral: "Desenrotllament socioafectiu",
      idCourse: "39",
    },
    {
      code: "0017",
      cliteral: "Habilidades sociales",
      vliteral: "Habilitats socials",
      idCourse: "39",
    },
    {
      code: "0018",
      cliteral: "IntervenciÃ³n con familias y atenc.",
      vliteral: "IntervenciÃ³ amb famÃ­lies i atenciÃ³ ",
      idCourse: "39",
    },
    {
      code: "0020",
      cliteral: "Primeros auxilios",
      vliteral: "Primers auxilis",
      idCourse: "3",
    },
    {
      code: "0021",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "39",
    },
    {
      code: "0022",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "39",
    },
    {
      code: "0026",
      cliteral: "Procesos bÃ¡sicos de pastelerÃ­a y reposterÃ­a",
      vliteral: "Processos bÃ sics de pastisseria i rebosteria",
      idCourse: "12",
    },
    {
      code: "0028",
      cliteral: "Postres en restauraciÃ³n",
      vliteral: "Postres en restauraciÃ³",
      idCourse: "12",
    },
    {
      code: "0031",
      cliteral: "Seguridad e higiene en la manipulaciÃ³n de alimentos",
      vliteral: "Seguretat i higiene en la manipulaciÃ³ d'aliments",
      idCourse: "12",
    },
    {
      code: "0045",
      cliteral: "Ofertas gastronÃ³micas",
      vliteral: "Ofertes gastronÃ²miques",
      idCourse: "12",
    },
    {
      code: "0046",
      cliteral: "PreelaboraciÃ³n y conservaciÃ³n de al",
      vliteral: "PreelaboraciÃ³ i conservaciÃ³ d'alime",
      idCourse: "12",
    },
    {
      code: "0047",
      cliteral: "TÃ©cnicas culinarias",
      vliteral: "TÃ¨cniques culinÃ ries",
      idCourse: "12",
    },
    {
      code: "0048",
      cliteral: "Productos culinarios",
      vliteral: "Productes culinaris",
      idCourse: "12",
    },
    {
      code: "0049",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "12",
    },
    {
      code: "0050",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "12",
    },
    {
      code: "0061",
      cliteral: "AnatomofisiologÃ­a y patologÃ­a bÃ¡sicas",
      vliteral: "Anatomofisiologia i patologia bÃ siques",
      idCourse: "4",
    },
    {
      code: "0099",
      cliteral: "DisposiciÃ³n y venta de productos",
      vliteral: "DisposiciÃ³ i venda de productes",
      idCourse: "4",
    },
    {
      code: "0100",
      cliteral: "Oficina de farmacia",
      vliteral: "Oficina de farmÃ cia",
      idCourse: "4",
    },
    {
      code: "0101",
      cliteral: "DispensaciÃ³n de productos farmaceÃºt",
      vliteral: "DispensaciÃ³ de productes farmacÃ¨ut.",
      idCourse: "4",
    },
    {
      code: "0102",
      cliteral: "DispensaciÃ³n de productos parafarm.",
      vliteral: "DispensaciÃ³ de productes parafarmac",
      idCourse: "4",
    },
    {
      code: "0103",
      cliteral: "Operaciones bÃ¡sicas de laboratorio",
      vliteral: "Operacions bÃ siques de laboratori",
      idCourse: "4",
    },
    {
      code: "0104",
      cliteral: "FormulaciÃ³n magistral",
      vliteral: "FormulaciÃ³ magistral",
      idCourse: "4",
    },
    {
      code: "0105",
      cliteral: "PromociÃ³n de la salud",
      vliteral: "PromociÃ³ de la salut",
      idCourse: "4",
    },
    {
      code: "0106",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "4",
    },
    {
      code: "0107",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "4",
    },
    {
      code: "0150",
      cliteral: "Operaciones bÃ¡sicas en bar-cafeterÃ­",
      vliteral: "Operacions bÃ siques en bar cafeteri",
      idCourse: "22",
    },
    {
      code: "0151",
      cliteral: "Operaciones bÃ¡sicas en restaurante",
      vliteral: "Operacions bÃ siques en restaurant",
      idCourse: "22",
    },
    {
      code: "0152",
      cliteral: "Servicios en bar-cafeterÃ­a",
      vliteral: "Servicis en bar cafeteria",
      idCourse: "22",
    },
    {
      code: "0153",
      cliteral: "Servicios en restaurante y eventos ",
      vliteral: "Servicis en restaurant i esdevenime",
      idCourse: "22",
    },
    {
      code: "0154",
      cliteral: "El vino y su servicio",
      vliteral: "El vi i el seu servici",
      idCourse: "22",
    },
    {
      code: "0155",
      cliteral: "TÃ©cnicas de comunicaciÃ³n en restaur",
      vliteral: "TÃ¨cniques de comunicaciÃ³ en restaur",
      idCourse: "22",
    },
    {
      code: "0156",
      cliteral: "InglÃ©s",
      vliteral: "AnglÃ©s",
      idCourse: "18",
    },
    {
      code: "0157",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "22",
    },
    {
      code: "0158",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "22",
    },
    {
      code: "0179",
      cliteral: "InglÃ©s",
      vliteral: "AnglÃ©s",
      idCourse: "28",
    },
    {
      code: "0180",
      cliteral: "Segunda lengua extranjera",
      vliteral: "Segona Llengua estrangera",
      idCourse: "38",
    },
    {
      code: "0210",
      cliteral:
        "OrganizaciÃ³n de la atenciÃ³n a las personas en situaciÃ³n dedependencia",
      vliteral:
        "OrganitzaciÃ³ de l'atenciÃ³ a les persones en situaciÃ³ de dependÃ¨ncia",
      idCourse: "3",
    },
    {
      code: "0211",
      cliteral: "Destrezas sociales",
      vliteral: "Destreses socials",
      idCourse: "3",
    },
    {
      code: "0212",
      cliteral:
        "CaracterÃ­sticas y necesidades de las personas en situaciÃ³n de dependencia",
      vliteral:
        "CaracterÃ­stiques i necessitats de les persones en situaciÃ³ de dependÃ¨ncia",
      idCourse: "3",
    },
    {
      code: "0213",
      cliteral: "AtenciÃ³n y apoyo psicosocial",
      vliteral: "AtenciÃ³ i suport psicosocial",
      idCourse: "3",
    },
    {
      code: "0214",
      cliteral: "Apoyo a la comunicaciÃ³n",
      vliteral: "Suport a la comunicaciÃ³",
      idCourse: "3",
    },
    {
      code: "0215",
      cliteral: "Apoyo domiciliario",
      vliteral: "Suport domiciliari",
      idCourse: "3",
    },
    {
      code: "0216",
      cliteral: "AtenciÃ³n sanitaria",
      vliteral: "AtenciÃ³ sanitÃ ria",
      idCourse: "3",
    },
    {
      code: "0217",
      cliteral: "AtenciÃ³n higiÃ©nica",
      vliteral: "AtenciÃ³ higiÃ¨nica",
      idCourse: "3",
    },
    {
      code: "0218",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral.",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral.",
      idCourse: "3",
    },
    {
      code: "0219",
      cliteral: "Empresa e iniciativa emprendedora.",
      vliteral: "Empresa i iniciativa emprenedora.",
      idCourse: "3",
    },
    {
      code: "0221",
      cliteral: "Montaje y mantenimiento de equipos",
      vliteral: "Muntatge i manteniment d'equips",
      idCourse: "24",
    },
    {
      code: "0222",
      cliteral: "Sistemas operativos monopuesto",
      vliteral: "Sistemes operatius monolloc",
      idCourse: "24",
    },
    {
      code: "0223",
      cliteral: "Aplicaciones ofimÃ¡ticas",
      vliteral: "Aplicacions ofimÃ tiques",
      idCourse: "24",
    },
    {
      code: "0224",
      cliteral: "Sistemas operativos en red",
      vliteral: "Sistemes operatius en xarxa",
      idCourse: "24",
    },
    {
      code: "0225",
      cliteral: "Redes locales",
      vliteral: "Xarxes locals",
      idCourse: "24",
    },
    {
      code: "0226",
      cliteral: "Seguridad informÃ¡tica",
      vliteral: "Seguretat informÃ tica",
      idCourse: "24",
    },
    {
      code: "0227",
      cliteral: "Servicios en red",
      vliteral: "Servicis en xarxa",
      idCourse: "24",
    },
    {
      code: "0228",
      cliteral: "Aplicaciones web",
      vliteral: "Aplicacions web",
      idCourse: "24",
    },
    {
      code: "0229",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "24",
    },
    {
      code: "0230",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "24",
    },
    {
      code: "028001",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "8",
    },
    {
      code: "028100",
      cliteral: "Relaciones en el equipo de trabajo",
      vliteral: "Relacions en l'equip de treball",
      idCourse: "8",
    },
    {
      code: "028501",
      cliteral: "Operaciones administrativas y documentaciÃ³n sanitaria",
      vliteral: "Operacions administratives i documentaciÃ³ sanitÃ ria",
      idCourse: "8",
    },
    {
      code: "028502",
      cliteral: "TÃ©cnicas bÃ¡sicas de enfermerÃ­a",
      vliteral: "TÃ¨cniques bÃ siques d'infermeria",
      idCourse: "8",
    },
    {
      code: "028503",
      cliteral: "Higiene del medio hospitalario y limpieza de material",
      vliteral: "Higiene del medi hospitalari i neteja de material",
      idCourse: "8",
    },
    {
      code: "028504",
      cliteral: "PromociÃ³n de la salud y apoyo psicolÃ³gico al paciente",
      vliteral: "PromociÃ³ de la salut i suport psicolÃ²gic al pacient",
      idCourse: "8",
    },
    {
      code: "028505",
      cliteral: "TÃ©cnicas de ayuda odontolÃ³gica/estomatolÃ³gica",
      vliteral: "TÃ¨cniques d'ajuda odontolÃ²gica/estomatolÃ²gica",
      idCourse: "8",
    },
    {
      code: "029001",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "54",
    },
    {
      code: "029506",
      cliteral: "OrganizaciÃ³n y gestiÃ³n de la unidad",
      vliteral: "OrganitzaciÃ³ i gestiÃ³ de la unitat ",
      idCourse: "54",
    },
    {
      code: "029507",
      cliteral: "Aguas de uso y consumo",
      vliteral: "AigÃ¼es d'Ãºs i consum",
      idCourse: "54",
    },
    {
      code: "029508",
      cliteral: "Residuos sÃ³lidos y medio construido",
      vliteral: "Residus sÃ²lids i medi construÃ¯t",
      idCourse: "54",
    },
    {
      code: "029509",
      cliteral: "Control y vigilancia de la contamin",
      vliteral: "Control i vigilÃ ncia de la contam.",
      idCourse: "54",
    },
    {
      code: "029510",
      cliteral: "ContaminaciÃ³n atmosfÃ©rica, ruidos ",
      vliteral: "ContaminaciÃ³ atmosfÃ¨rica, sorolls",
      idCourse: "54",
    },
    {
      code: "029511",
      cliteral: "Productos quÃ­micos y vectores ",
      vliteral: "Productes quÃ­mics i vectors ",
      idCourse: "54",
    },
    {
      code: "029512",
      cliteral: "EducaciÃ³n sanitaria y promociÃ³n ",
      vliteral: "EducaciÃ³ sanitÃ ria i promociÃ³ ",
      idCourse: "54",
    },
    {
      code: "0337",
      cliteral: "Contexto de la intervenciÃ³n social",
      vliteral: "Context de la intervenciÃ³ social",
      idCourse: "44",
    },
    {
      code: "0338",
      cliteral: "InserciÃ³n sociolaboral",
      vliteral: "InserciÃ³ sociolaboral",
      idCourse: "44",
    },
    {
      code: "0339",
      cliteral: "AtenciÃ³n a las unidades de convivencia",
      vliteral: "AtenciÃ³ a les unitats de convivÃ¨ncia",
      idCourse: "44",
    },
    {
      code: "0340",
      cliteral: "MediaciÃ³n comunitaria",
      vliteral: "MediaciÃ³ comunitÃ ria",
      idCourse: "44",
    },
    {
      code: "0341",
      cliteral: "Apoyo a la intervenciÃ³n educativa",
      vliteral: "Suport a la intervenciÃ³ educativa",
      idCourse: "44",
    },
    {
      code: "0342",
      cliteral: "PromociÃ³n de la autonomÃ­a personal",
      vliteral: "PromociÃ³ de l'autonomia personal",
      idCourse: "44",
    },
    {
      code: "0343",
      cliteral: "Sistemas alternativos y aumentativos de comunicaciÃ³n",
      vliteral: "Sistemes alternatius i augmentatius de comunicaciÃ³",
      idCourse: "44",
    },
    {
      code: "0344",
      cliteral: "MetodologÃ­a de la intervenciÃ³n social",
      vliteral: "Metodologia de la intervenciÃ³ social",
      idCourse: "44",
    },
    {
      code: "0346",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "44",
    },
    {
      code: "0347",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "44",
    },
    {
      code: "0369",
      cliteral: "ImplantaciÃ³n de Sistemas Operativos",
      vliteral: "ImplantaciÃ³ de Sistemes Operatius",
      idCourse: "30",
    },
    {
      code: "0370",
      cliteral: "PlanificaciÃ³n y AdministraciÃ³n de Redes",
      vliteral: "PlanificaciÃ³ i AdministraciÃ³ de Xarxes",
      idCourse: "30",
    },
    {
      code: "0371",
      cliteral: "Fundamentos de Hardware",
      vliteral: "Fonaments de Maquinari",
      idCourse: "30",
    },
    {
      code: "0372",
      cliteral: "GestiÃ³n de Bases de Datos",
      vliteral: "GestiÃ³ de Bases de Dades",
      idCourse: "30",
    },
    {
      code: "0373",
      cliteral: "Lenguajes de marcas y sistemas de gestiÃ³n de informaciÃ³n",
      vliteral: "Llenguatges de marques i sistemes de gestiÃ³ d'informaciÃ³",
      idCourse: "30",
    },
    {
      code: "0374",
      cliteral: "AdministraciÃ³n de Sistemas Operativos",
      vliteral: "AdministraciÃ³ de Sistemes Operatius",
      idCourse: "30",
    },
    {
      code: "0375",
      cliteral: "Servicios de Red e Internet",
      vliteral: "Servicis de Xarxa i Internet",
      idCourse: "30",
    },
    {
      code: "0376",
      cliteral: "ImplantaciÃ³n de Aplicaciones Web",
      vliteral: "ImplantaciÃ³ d'Aplicacions Web",
      idCourse: "30",
    },
    {
      code: "0377",
      cliteral: "AdministraciÃ³n de Sistemas Gestores de Bases de Datos",
      vliteral: "AdministraciÃ³ de Sistemes Gestors de Bases de Dades",
      idCourse: "30",
    },
    {
      code: "0378",
      cliteral: "Seguridad y Alta Disponibilidad",
      vliteral: "Seguretat i Alta Disponibilitat",
      idCourse: "30",
    },
    {
      code: "0380",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "30",
    },
    {
      code: "0381",
      cliteral: "Empresa e Iniciativa emprendedora",
      vliteral: "Empresa i Iniciativa emprenedora",
      idCourse: "30",
    },
    {
      code: "0437",
      cliteral: "ComunicaciÃ³n empresarial y atenciÃ³n al cliente",
      vliteral: "ComunicaciÃ³ empresarial i atenciÃ³ al client",
      idCourse: "18",
    },
    {
      code: "0438",
      cliteral: "Operaciones administrativa de compra-venta",
      vliteral: "Operacions administrativa de compra-venda",
      idCourse: "18",
    },
    {
      code: "0439",
      cliteral: "Empresa y administraciÃ³n",
      vliteral: "Empresa i administraciÃ³",
      idCourse: "18",
    },
    {
      code: "0440",
      cliteral: "Tratamiento informÃ¡tico de la informaciÃ³n ",
      vliteral: "Tractament informÃ tic de la informaciÃ³ ",
      idCourse: "18",
    },
    {
      code: "0441",
      cliteral: "TÃ©cnica contable",
      vliteral: "TÃ¨cnica comptable",
      idCourse: "18",
    },
    {
      code: "0442",
      cliteral: "Operaciones administrativas de recursos humanos",
      vliteral: "Operacions administratives de recursos humans",
      idCourse: "18",
    },
    {
      code: "0443",
      cliteral: "Tratamiento de la documentaciÃ³n contable",
      vliteral: "Tractament de la documentaciÃ³ comptable",
      idCourse: "18",
    },
    {
      code: "0446",
      cliteral: "Empresa en el aula",
      vliteral: "Empresa en l'aula",
      idCourse: "18",
    },
    {
      code: "0448",
      cliteral: "Operaciones auxiliares de gestiÃ³n de tesorerÃ­a",
      vliteral: "Operacions auxiliars de gestiÃ³ de tresoreria",
      idCourse: "18",
    },
    {
      code: "0449",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "18",
    },
    {
      code: "0483",
      cliteral: "Sistemas informÃ¡ticos",
      vliteral: "Sistemes informÃ tics",
      idCourse: "32",
    },
    {
      code: "0484",
      cliteral: "Bases de Datos",
      vliteral: "Bases de Dades",
      idCourse: "32",
    },
    {
      code: "0485",
      cliteral: "ProgramaciÃ³n",
      vliteral: "ProgramaciÃ³",
      idCourse: "32",
    },
    {
      code: "0486",
      cliteral: "Acceso a datos",
      vliteral: "AccÃ©s a dades",
      idCourse: "32",
    },
    {
      code: "0487",
      cliteral: "Entornos de desarrollo",
      vliteral: "Entorns de desenrotllament",
      idCourse: "32",
    },
    {
      code: "0488",
      cliteral: "Desarrollo de interfaces",
      vliteral: "Desenrotllament d'interfÃ­cies",
      idCourse: "32",
    },
    {
      code: "0489",
      cliteral: "ProgramaciÃ³n multimedia y dispositivos mÃ³viles",
      vliteral: "ProgramaciÃ³ multimÃ¨dia i dispositius mÃ²bils",
      idCourse: "32",
    },
    {
      code: "0490",
      cliteral: "ProgramaciÃ³n de servicios y procesos",
      vliteral: "ProgramaciÃ³ de servicis i processos",
      idCourse: "32",
    },
    {
      code: "0491",
      cliteral: "Sistemas de gestiÃ³n empresarial",
      vliteral: "Sistemes de gestiÃ³ empresarial",
      idCourse: "32",
    },
    {
      code: "0493",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "32",
    },
    {
      code: "0494",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "32",
    },
    {
      code: "0496",
      cliteral: "Control del aprovisionamiento de materias primas",
      vliteral: "Control de l'aprovisionament  de matÃ¨ries primeres",
      idCourse: "36",
    },
    {
      code: "0497",
      cliteral: "Procesos de preelaboraciÃ³n y conservaciÃ³n en cocina",
      vliteral: "Processos de preelaboraciÃ³ i conservaciÃ³ en cuina",
      idCourse: "36",
    },
    {
      code: "0498",
      cliteral: "Elaboraciones de pastelerÃ­a y reposterÃ­a",
      vliteral: "Elaboracions de pastisseria i rebosteria",
      idCourse: "36",
    },
    {
      code: "0499",
      cliteral: "Procesos de elaboraciÃ³n culinaria",
      vliteral: "Processos d'elaboraciÃ³ culinÃ ria",
      idCourse: "36",
    },
    {
      code: "0500",
      cliteral: "GestiÃ³n de la producciÃ³n en cocina",
      vliteral: "GestiÃ³n de la producciÃ³n en cocina",
      idCourse: "36",
    },
    {
      code: "0501",
      cliteral:
        "GestiÃ³n de la calidad y de la seguridad e higiene alimentaria",
      vliteral:
        "GestiÃ³ de la qualitat i de la seguretat i higiene alimentÃ ries",
      idCourse: "36",
    },
    {
      code: "0502",
      cliteral: "GastronomÃ­a y nutriciÃ³n",
      vliteral: "Gastronomia i nutriciÃ³",
      idCourse: "36",
    },
    {
      code: "0503",
      cliteral: "GestiÃ³n administrativa y comercial en restauraciÃ³n",
      vliteral: "GestiÃ³ administrativa i comercial en restauraciÃ³",
      idCourse: "36",
    },
    {
      code: "0504",
      cliteral: "Recursos humanos y direcciÃ³n de equipos en restauraciÃ³n",
      vliteral: "Recursos humans i direcciÃ³ d'equips en restauraciÃ³",
      idCourse: "36",
    },
    {
      code: "0506",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "36",
    },
    {
      code: "0507",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "36",
    },
    {
      code: "0509",
      cliteral: "Procesos de servicios en bar-cafeterÃ­a",
      vliteral: "Processos de servicis en bar-cafeteria",
      idCourse: "38",
    },
    {
      code: "0510",
      cliteral: "Procesos de servicios en restaurante",
      vliteral: "Processos de servicis en restaurant",
      idCourse: "38",
    },
    {
      code: "0511",
      cliteral: "SumillerÃ­a",
      vliteral: "Sumilleria",
      idCourse: "38",
    },
    {
      code: "0512",
      cliteral:
        "PlanificaciÃ³n y direcciÃ³n de servicios y eventos en restauraciÃ³n",
      vliteral:
        "PlanificaciÃ³ i direcciÃ³ de servicis i esdeveniments en restauraciÃ³",
      idCourse: "38",
    },
    {
      code: "0514",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "38",
    },
    {
      code: "0515",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "38",
    },
    {
      code: "0612",
      cliteral: "Desarrollo WEB en entorno cliente",
      vliteral: "Desenrotllament WEB en entorn client",
      idCourse: "35",
    },
    {
      code: "0613",
      cliteral: "Desarrollo WEB en entorno servidor",
      vliteral: "Desenrotllament WEB en entorn servidor",
      idCourse: "35",
    },
    {
      code: "0614",
      cliteral: "Despliegue de aplicaciones WEB",
      vliteral: "Desplegament d'aplicacions WEB",
      idCourse: "35",
    },
    {
      code: "0615",
      cliteral: "DiseÃ±o de interfaces WEB",
      vliteral: "Disseny d'interfÃ­cies WEB",
      idCourse: "35",
    },
    {
      code: "0617",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "35",
    },
    {
      code: "0618",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "35",
    },
    {
      code: "0633",
      cliteral: "TÃ©cnicas de higiene facial y corporal",
      vliteral: "TÃ¨cniques d'higiene facial i corporal",
      idCourse: "16",
    },
    {
      code: "0634",
      cliteral: "Maquillaje",
      vliteral: "Maquillatge",
      idCourse: "16",
    },
    {
      code: "0635",
      cliteral: "DEPILACIÃ“N MECÃNICA Y DECOLORACIÃ“N DEL VELLO",
      vliteral: "DEPILACIÃ“ MECÃ€NICA I DECOLORACIÃ“ DEL BORRISSOL",
      idCourse: "16",
    },
    {
      code: "0636",
      cliteral: "EstÃ©tica de manos y pies",
      vliteral: "EstÃ¨tica de mans i peus",
      idCourse: "16",
    },
    {
      code: "0637",
      cliteral: "TÃ‰CNICAS DE UÃ‘AS ARTIFICIALES",
      vliteral: "TÃˆCNIQUES D'UNGLES ARTIFICIALS",
      idCourse: "16",
    },
    {
      code: "0638",
      cliteral: "AnÃ¡lisis estÃ©tico",
      vliteral: "AnÃ lisi estÃ¨tica",
      idCourse: "16",
    },
    {
      code: "0639",
      cliteral: "ACTIVIDADES EN CABINA DE ESTÃ‰TICA",
      vliteral: "ACTIVITATS EN CABINA D'ESTÃˆTICA",
      idCourse: "16",
    },
    {
      code: "0640",
      cliteral: "Imagen corporal y hÃ¡bitos saludables",
      vliteral: "Imatge corporal i hÃ bits saludables",
      idCourse: "16",
    },
    {
      code: "0641",
      cliteral: "CosmetologÃ­a para estÃ©tica y belleza",
      vliteral: "Cosmetologia per a estÃ¨tica i bellesa",
      idCourse: "16",
    },
    {
      code: "0642",
      cliteral: "PERFUMERÃA Y COSMÃ‰TICA NATURAL",
      vliteral: "PERFUMERIA I COSMÃˆTICA NATURAL",
      idCourse: "16",
    },
    {
      code: "0643",
      cliteral: "Marketing y venta en imagen personal",
      vliteral: "MÃ rqueting i venda en imatge personal.",
      idCourse: "16",
    },
    {
      code: "0644",
      cliteral: "FORMACIÃ“N Y ORIENTACIÃ“N LABORAL",
      vliteral: "FORMACIÃ“ I ORIENTACIÃ“ LABORAL",
      idCourse: "16",
    },
    {
      code: "0645",
      cliteral: "EMPRESA E INICIATIVA EMPRENDEDORA",
      vliteral: "EMPRESA I INICIATIVA EMPRENEDORA",
      idCourse: "16",
    },
    {
      code: "0647",
      cliteral: "GestiÃ³n de la documentaciÃ³n jurÃ­dica y empresarial",
      vliteral: "GestiÃ³ de la documentaciÃ³ jurÃ­dica i empresarial",
      idCourse: "28",
    },
    {
      code: "0648",
      cliteral: "Recursos humanos y responsabilidad social corporativa",
      vliteral: "Recursos humans i responsabilitat social corporativa ",
      idCourse: "28",
    },
    {
      code: "0649",
      cliteral: "OfimÃ¡tica y proceso de la informaciÃ³n",
      vliteral: "OfimÃ tica i procÃ©s de la informaciÃ³",
      idCourse: "28",
    },
    {
      code: "0650",
      cliteral: "Proceso integral de la actividad comercial",
      vliteral: "ProcÃ©s integral de l'activitat comercial",
      idCourse: "28",
    },
    {
      code: "0651",
      cliteral: "ComunicaciÃ³n y atenciÃ³n al cliente",
      vliteral: "ComunicaciÃ³ i atenciÃ³ al client",
      idCourse: "28",
    },
    {
      code: "0652",
      cliteral: "GestiÃ³n de recursos humanos",
      vliteral: "GestiÃ³ de recursos humans",
      idCourse: "28",
    },
    {
      code: "0653",
      cliteral: "GestiÃ³n financiera",
      vliteral: "GestiÃ³ financera ",
      idCourse: "28",
    },
    {
      code: "0654",
      cliteral: "Contabilidad y fiscalidad",
      vliteral: "Comptabilitat i fiscalitat",
      idCourse: "28",
    },
    {
      code: "0655",
      cliteral: "GestiÃ³n logÃ­stica y comercial",
      vliteral: "GestiÃ³ logÃ­stica i comercial",
      idCourse: "28",
    },
    {
      code: "0656",
      cliteral: "SimulaciÃ³n empresarial",
      vliteral: "SimulaciÃ³ empresarial",
      idCourse: "28",
    },
    {
      code: "0658",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "28",
    },
    {
      code: "0665",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "29",
    },
    {
      code: "0744",
      cliteral: "AparatologÃ­a estÃ©tica",
      vliteral: "Aparellologia estÃ¨tica ",
      idCourse: "42",
    },
    {
      code: "0745",
      cliteral: "EstÃ©tica hidrotermal",
      vliteral: "EstÃ¨tica hidrotermal",
      idCourse: "42",
    },
    {
      code: "0746",
      cliteral: "DepilaciÃ³n avanzada",
      vliteral: "DepilaciÃ³ avanÃ§ada",
      idCourse: "42",
    },
    {
      code: "0747",
      cliteral: "Masaje estÃ©tico",
      vliteral: "Massatge estÃ¨tic",
      idCourse: "42",
    },
    {
      code: "0748",
      cliteral: "Drenaje estÃ©tico y tÃ©cnicas por presiÃ³n",
      vliteral: "Drenatge estÃ¨tic i tÃ¨cniques per pressiÃ³",
      idCourse: "42",
    },
    {
      code: "0749",
      cliteral: "MicropigmentaciÃ³n",
      vliteral: "MicropigmentaciÃ³",
      idCourse: "42",
    },
    {
      code: "0750",
      cliteral: "Procesos fisiolÃ³gicos y de higiene en imagen personal ",
      vliteral: "Processos fisiolÃ²gics i d'higiene en imatge personal",
      idCourse: "42",
    },
    {
      code: "0751",
      cliteral: "DermoestÃ©tica",
      vliteral: "DermoestÃ¨tica",
      idCourse: "42",
    },
    {
      code: "0752",
      cliteral: "CosmÃ©tica aplicada a estÃ©tica y bienestar ",
      vliteral: "CosmÃ¨tica aplicada a estÃ¨tica i benestar",
      idCourse: "42",
    },
    {
      code: "0753",
      cliteral: "Tratamientos estÃ©ticos integrales",
      vliteral: "Tractaments estÃ¨tics integrals",
      idCourse: "42",
    },
    {
      code: "0755",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral ",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "42",
    },
    {
      code: "0756",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "42",
    },
    {
      code: "0831",
      cliteral: "Teleasistencia",
      vliteral: "TeleasistÃ¨ncia",
      idCourse: "3",
    },
    {
      code: "0842",
      cliteral: "Peinados y recogidos",
      vliteral: "Pentinats i arreplegats",
      idCourse: "20",
    },
    {
      code: "0843",
      cliteral: "ColoraciÃ³n capilar",
      vliteral: "ColoraciÃ³ capilÂ·lar",
      idCourse: "20",
    },
    {
      code: "0844",
      cliteral: "CosmÃ©tica para peluquerÃ­a",
      vliteral: "CosmÃ¨tica per a perruqueria",
      idCourse: "20",
    },
    {
      code: "0845",
      cliteral: "TÃ©cnicas de corte del cabello",
      vliteral: "TÃ¨cniques de tall del cabell",
      idCourse: "20",
    },
    {
      code: "0846",
      cliteral: "Cambios de forma permanente del cabello",
      vliteral: "Canvis de forma permanent del cabell",
      idCourse: "20",
    },
    {
      code: "0848",
      cliteral: "PeluquerÃ­a y estilismo masculino",
      vliteral: "Perruqueria i estilisme masculÃ­",
      idCourse: "20",
    },
    {
      code: "0849",
      cliteral: "AnÃ¡lisis capilar",
      vliteral: "AnÃ lisi capilÂ·lar",
      idCourse: "20",
    },
    {
      code: "0851",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral.",
      idCourse: "20",
    },
    {
      code: "0852",
      cliteral: "Empresa e iniciativa emprendedora.",
      vliteral: "Empresa i iniciativa emprenedora.",
      idCourse: "20",
    },
    {
      code: "1123",
      cliteral: "ACTIVIDADES DE OCIO Y TIEMPO LIBRE",
      vliteral: "ACTIVITATS D'OCI I TEMPS LLIURE",
      idCourse: "56",
    },
    {
      code: "1124",
      cliteral: "DINAMIZACIÃ“N GRUPAL",
      vliteral: "DINAMITZACIÃ“ GRUPAL",
      idCourse: "56",
    },
    {
      code: "1125",
      cliteral: "ANIMACIÃ“N Y GESTIÃ“N CULTURAL",
      vliteral: "ANIMACIÃ“ I GESTIÃ“ CULTURAL",
      idCourse: "56",
    },
    {
      code: "1126",
      cliteral: "ANIMACIÃ“N TURÃSTICA",
      vliteral: "ANIMACIÃ“ TURÃSTICA",
      idCourse: "56",
    },
    {
      code: "1128",
      cliteral: "Desarrollo comunitario",
      vliteral: "Desenrotllament comunitari",
      idCourse: "56",
    },
    {
      code: "1129",
      cliteral: "INFORMACIÃ“N JUVENIL",
      vliteral: "INFORMACIÃ“ JUVENIL",
      idCourse: "56",
    },
    {
      code: "1130",
      cliteral: "INTERVENCIÃ“N SOCIOEDUCATIVA CON JÃ“VENES",
      vliteral: "INTERVENCIÃ“ SOCIOEDUCATIVA AMB JÃ“VENS",
      idCourse: "56",
    },
    {
      code: "1131",
      cliteral: "CONTEXTO DE LA ANIMACIÃ“N SOCIOCULTURAL",
      vliteral: "CONTEXT DE L'ANIMACIÃ“ SOCIOCULTURAL",
      idCourse: "56",
    },
    {
      code: "1133",
      cliteral: "FORMACIÃ“N Y ORIENTACIÃ“N LABORAL",
      vliteral: "FORMACIÃ“ I ORIENTACIÃ“ LABORAL",
      idCourse: "56",
    },
    {
      code: "1134",
      cliteral: "EMPRESA E INICIATIVA EMPRENDEDORA",
      vliteral: "EMPRESA I INICIATIVA EMPRENEDORA",
      idCourse: "56",
    },
    {
      code: "1345",
      cliteral: "AtenciÃ³n al paciente",
      vliteral: "AtenciÃ³ al pacient",
      idCourse: "51",
    },
    {
      code: "1346",
      cliteral: "Fundamentos fÃ­sicos y equipos",
      vliteral: "Fonaments fÃ­sics i equips",
      idCourse: "51",
    },
    {
      code: "1347",
      cliteral: "AnatomÃ­a por la imagen",
      vliteral: "Anatomia per la imatge",
      idCourse: "51",
    },
    {
      code: "1348",
      cliteral: "ProtecciÃ³n radiolÃ³gica",
      vliteral: "ProtecciÃ³ radiolÃ²gica",
      idCourse: "51",
    },
    {
      code: "1349",
      cliteral: "TÃ©cnicas de radiologÃ­a simple",
      vliteral: "TÃ¨cniques de radiologia simple",
      idCourse: "51",
    },
    {
      code: "1350",
      cliteral: "TÃ©cnicas de radiologÃ­a especial",
      vliteral: "TÃ¨cniques de radiologia especial",
      idCourse: "51",
    },
    {
      code: "1351",
      cliteral: "TÃ©cnicas de tomografÃ­a computarizada y ecografÃ­a",
      vliteral: "TÃ¨cniques de tomografia computada i ecografia",
      idCourse: "51",
    },
    {
      code: "1352",
      cliteral: "TÃ©cnicas de imagen por resonancia magnÃ©tica",
      vliteral: "TÃ¨cniques dÂ¿imatge per ressonÃ ncia magnÃ¨tica",
      idCourse: "51",
    },
    {
      code: "1353",
      cliteral: "TÃ©cnicas de imagen en medicina nuclear",
      vliteral: "TÃ¨cniques dÂ¿imatge en medicina nuclear",
      idCourse: "51",
    },
    {
      code: "1354",
      cliteral: "TÃ©cnicas de radiofarmacia",
      vliteral: "TÃ¨cniques de radiofarmÃ cia",
      idCourse: "51",
    },
    {
      code: "1355",
      cliteral: "Proyecto de imagen para el diagnÃ³stico y medicina nuclear",
      vliteral: "Projecte dÂ¿Imatge per al DiagnÃ²stic i Medicina Nuclear",
      idCourse: "51",
    },
    {
      code: "1356",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "51",
    },
    {
      code: "1357",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "51",
    },
    {
      code: "1358",
      cliteral: "FormaciÃ³n en centros de trabajo",
      vliteral: "FormaciÃ³ en Centres de Treball",
      idCourse: "51",
    },
    {
      code: "1367",
      cliteral: "GestiÃ³n de muestras biolÃ³gicas",
      vliteral: "GestiÃ³ de mostres biolÃ²giques",
      idCourse: "45",
    },
    {
      code: "1368",
      cliteral: "TÃ©cnicas generales de laboratorio",
      vliteral: "TÃ¨cniques generals de laboratori",
      idCourse: "45",
    },
    {
      code: "1369",
      cliteral: "BiologÃ­a molecular y citogenÃ©tica",
      vliteral: "Biologia molecular i citogenÃ¨tica",
      idCourse: "45",
    },
    {
      code: "1370",
      cliteral: "FisiopatologÃ­a general",
      vliteral: "Fisiopatologia general",
      idCourse: "45",
    },
    {
      code: "1371",
      cliteral: "AnÃ¡lisis bioquÃ­mico",
      vliteral: "AnÃ lisi bioquÃ­mica",
      idCourse: "45",
    },
    {
      code: "1372",
      cliteral: "TÃ©cnicas de inmunodiagnÃ³stico",
      vliteral: "TÃ¨cniques dÂ¿immunodiagnÃ²stic",
      idCourse: "45",
    },
    {
      code: "1373",
      cliteral: "MicrobiologÃ­a clÃ­nica",
      vliteral: "Microbiologia clÃ­nica",
      idCourse: "45",
    },
    {
      code: "1374",
      cliteral: "TÃ©cnicas de anÃ¡lisis hematolÃ³gico",
      vliteral: "TÃ¨cniques dÂ¿anÃ lisi hematolÃ²gica",
      idCourse: "45",
    },
    {
      code: "1376",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "45",
    },
    {
      code: "1377",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "45",
    },
    {
      code: "1546",
      cliteral: "Sistemas de gestiÃ³n ambiental",
      vliteral: "Sistemes de gestiÃ³ ambiental",
      idCourse: "58",
    },
    {
      code: "1547",
      cliteral: "EducaciÃ³n para la salud y el medio ambiente",
      vliteral: "EducaciÃ³ per a la salut i el medi ambient",
      idCourse: "58",
    },
    {
      code: "1548",
      cliteral: "Control de aguas",
      vliteral: "Control d'aigÃ¼es",
      idCourse: "58",
    },
    {
      code: "1549",
      cliteral: "Control de residuos",
      vliteral: "Control de residus",
      idCourse: "58",
    },
    {
      code: "1550",
      cliteral: "Salud y riesgos del medio construido",
      vliteral: "Salut i riscos del mig construÃ¯t",
      idCourse: "58",
    },
    {
      code: "1551",
      cliteral: "Control y seguridad alimentaria",
      vliteral: "Control i seguretat alimentÃ ria",
      idCourse: "58",
    },
    {
      code: "1552",
      cliteral: "ContaminaciÃ³n ambiental y atmosfÃ©rica",
      vliteral: "ContaminaciÃ³ ambiental i atmosfÃ¨rica",
      idCourse: "58",
    },
    {
      code: "1553",
      cliteral: "Control de organismos nocivos",
      vliteral: "Control d'organismes nocius",
      idCourse: "58",
    },
    {
      code: "1554",
      cliteral: "Unidad de salud ambiental",
      vliteral: "Unitat de salut ambiental",
      idCourse: "58",
    },
    {
      code: "1556",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral",
      idCourse: "58",
    },
    {
      code: "1557",
      cliteral: "Empresa e iniciativa emprendedora",
      vliteral: "Empresa i iniciativa emprenedora",
      idCourse: "58",
    },
    {
      code: "3005",
      cliteral: "AtenciÃ³n al cliente",
      vliteral: "AtenciÃ³ al client",
      idCourse: "57",
    },
    {
      code: "3009",
      cliteral: "Ciencias Aplicadas I",
      vliteral: "CiÃ¨ncies aplicades I",
      idCourse: "57",
    },
    {
      code: "3011",
      cliteral: "ComunicaciÃ³n y Sociedad I",
      vliteral: "ComunicaciÃ³ i societat I",
      idCourse: "57",
    },
    {
      code: "3011cv",
      cliteral: "Castellano-Valenciano",
      vliteral: "CastellÃ -ValenciÃ ",
      idCourse: "57",
    },
    {
      code: "3011e",
      cliteral: "Lengua Extranjera",
      vliteral: "Llengua Estrangera",
      idCourse: "57",
    },
    {
      code: "3011s",
      cliteral: "Ciencias Sociales ",
      vliteral: "CiÃ¨ncies Socials ",
      idCourse: "57",
    },
    {
      code: "3012",
      cliteral: "ComunicaciÃ³n y Sociedad II",
      vliteral: "ComunicaciÃ³ i Societat II",
      idCourse: "57",
    },
    {
      code: "3012cv",
      cliteral: "Castellano-Valenciano II",
      vliteral: "CastellÃ -ValenciÃ  II",
      idCourse: "57",
    },
    {
      code: "3012e",
      cliteral: "Lengua Extranjera II",
      vliteral: "Llengua Estrangera II",
      idCourse: "57",
    },
    {
      code: "3012s",
      cliteral: "Ciencias Sociales II",
      vliteral: "CiÃ¨ncies Socials II",
      idCourse: "57",
    },
    {
      code: "3042",
      cliteral: "Ciencias Aplicadas II",
      vliteral: "CiÃ¨ncies Aplicades II",
      idCourse: "57",
    },
    {
      code: "3060",
      cliteral: "PreparaciÃ³n del entorno profesional",
      vliteral: "PreparaciÃ³ de l'entorn professional",
      idCourse: "57",
    },
    {
      code: "3061",
      cliteral: "Cuidados estÃ©ticos bÃ¡sicos de uÃ±as",
      vliteral: "Cures estÃ¨tiques bÃ siques d'ungles",
      idCourse: "57",
    },
    {
      code: "3062",
      cliteral: "DepilaciÃ³n mecÃ¡nica y decoloraciÃ³n del vello superfluo",
      vliteral: "DepilaciÃ³ mecÃ nica i decoloraciÃ³ del borrissol superflu",
      idCourse: "57",
    },
    {
      code: "3063",
      cliteral: "Maquillaje",
      vliteral: "Maquillatge",
      idCourse: "57",
    },
    {
      code: "3064",
      cliteral: "Lavado y cambios de forma del cabello",
      vliteral: "Llavat i canvis de forma del cabell",
      idCourse: "57",
    },
    {
      code: "3065",
      cliteral: "Cambio de color del cabello",
      vliteral: "Canvi de color del cabell",
      idCourse: "57",
    },
    {
      code: "3067p",
      cliteral: "FormaciÃ³n en centros de trabajo (UF1)",
      vliteral: "FormaciÃ³ en centres de treball (UF1)",
      idCourse: "57",
    },
    {
      code: "5021",
      cliteral: "Incidentes de ciberseguridad",
      vliteral: "Incidents de ciberseguretat",
      idCourse: "59",
    },
    {
      code: "5022",
      cliteral: "Bastionado de redes y sistemas",
      vliteral: "Bastionado de xarxes i sistemes",
      idCourse: "59",
    },
    {
      code: "5023",
      cliteral: "Puesta en producciÃ³n segura",
      vliteral: "Posada en producciÃ³ segura",
      idCourse: "59",
    },
    {
      code: "5024",
      cliteral: "AnÃ¡lisis forense informÃ¡tico",
      vliteral: "AnÃ lisi forense informÃ tic",
      idCourse: "59",
    },
    {
      code: "5025",
      cliteral: "Hacking Ã©tico",
      vliteral: "Hacking Ã¨tic",
      idCourse: "59",
    },
    {
      code: "5026",
      cliteral: "Normativa de ciberseguridad",
      vliteral: "Normativa de ciberseguretat",
      idCourse: "59",
    },
    {
      code: "CV0001",
      cliteral:
        "InglÃ©s TÃ©cnico I-M / Horario reservado para la docencia en inglÃ©s",
      vliteral:
        "AnglÃ©s TÃ¨cnic I-M / Horari reservat per a la docÃ¨ncia en anglÃ©s",
      idCourse: "3",
    },
    {
      code: "CV0002",
      cliteral:
        "InglÃ©s TÃ©cnico II-M / Horario reservado para la docencia en inglÃ©s",
      vliteral:
        "AnglÃ©s TÃ¨cnic II-M / Horari reservat per a la docÃ¨ncia en anglÃ©s",
      idCourse: "3",
    },
    {
      code: "CV0003",
      cliteral:
        "InglÃ©s TÃ©cnico I-S / Horario reservado para la docencia en inglÃ©s",
      vliteral:
        "InglÃ©s TÃ©cnico I-S / Horario reservado para la docencia en inglÃ©s",
      idCourse: "28",
    },
    {
      code: "CV0004",
      cliteral:
        "InglÃ©s TÃ©cnico II-S / Horario reservado para la docencia en inglÃ©s",
      vliteral:
        "AnglÃ©s TÃ¨cnic II-S / Horari reservat per a la docÃ¨ncia en anglÃ©s",
      idCourse: "28",
    },
    {
      code: "CV0005",
      cliteral: "FormaciÃ³n y orientaciÃ³n laboral ",
      vliteral: "FormaciÃ³ i orientaciÃ³ laboral ",
      idCourse: "57",
    },
    {
      code: "CV0006",
      cliteral: "FormaciÃ³n y OrientaciÃ³n Laboral II",
      vliteral: "FormaciÃ³ i OrientaciÃ³ Laboral II",
      idCourse: "57",
    },
  ],
  sales: [
    {
      id: 1,
      idBook: 1,
      idUser: 2,
      date: "2023-03-01",
      status: 0,
    },
  ],
  users: [
    {
      id: 2,
      email: "ignasi.gomis.mullor@gmail.com",
      nick: "Ignasi",
    },
    {
      email: "juanseguravasco@gmail.com",
      nick: "Juan",
      id: 3,
    },
    {
      email: "marta@gmail.lan",
      nick: "Marta",
      id: 4,
    },
    {
      email: "Ximo@gmail.lan",
      nick: "Ximo",
      id: 5,
    },
  ],
  books: [
    {
      id: 1,
      idUser: 2,
      idModule: "5025",
      publisher: "Apunts",
      price: 12,
      pages: 25,
      status: "good",
      photo: "",
      comments: "",
      soldDate: "2023-02-01",
    },
    {
      idUser: 3,
      idModule: "5021",
      publisher: "McGraw-Hill",
      price: 75,
      pages: 273,
      status: "new",
      photo: "",
      comments: "Sense obrir",
      soldDate: "",
      id: 6,
    },
    {
      idUser: 4,
      idModule: "5021",
      publisher: "McGraw-Hill",
      price: 15,
      pages: 173,
      status: "bad",
      photo: "",
      comments: "Fet pols",
      soldDate: "",
      id: 7,
    },
    {
      idUser: 4,
      idModule: "5025",
      publisher: "McGraw-Hill",
      price: 15,
      pages: 173,
      status: "good",
      photo: "",
      comments: "",
      soldDate: "",
      id: 8,
    },
    {
      idUser: 4,
      idModule: "5025",
      publisher: "Apunts",
      price: 35,
      pages: 73,
      status: "good",
      photo: "",
      comments: "",
      soldDate: "",
      id: 9,
    },
    {
      idUser: 5,
      idModule: "5021",
      publisher: "Apunts",
      price: 5,
      pages: 57,
      status: "good",
      photo: "",
      comments: "",
      soldDate: "",
      id: 10,
    },
  ],
};

export default data;
